### ISSUE TITLE
Adopt SAML-Tracer in the SSP org

### ISSUE THREAD

**Issue by thijskh** [simplesamlphp/governance#18]
SAML-Tracer is a browser addon developed by UNINETT: https://github.com/Uninett/SAML-tracer/
It is a small but immensely useful thing, popular in and outside our community. There's periodic activity on Github and active contributions.

It seems that in recent years the maintenance has stalled. There are open PR's and a new release could be made and uploaded to the Firefox add-ons store, but this has not happened in two years.

I have asked UNINETT and they are willing to release ownership of it. One possible solution we see is that we give it a home under the SimpleSAMLphp organization. It's really too small to make it a project on its own with a support infrastructure.

We can give it a technical home on our Github. But it would also be nice if some of the Commons Conservancy support would extend to this project. It has a really high value-vs-effort ratio; I guess a few hours per quarter spent on it (review open issues/PR's, create a release of accumulated work) would be more than enough and help an even wider community than SSP currently serves.

**Comment by thijskh** [comment]
I've investigated how we can realise this should we decide to go through with it.

1. Transfer Github repo from Uninett org to SSP org. Olav or Andreas can do this since they already are admins in both (1 minute job). Or we can temporarily make Morten admin in SSP.
2. Transfer Mozilla AMO ownership of the extension from Uninett to an SSP group.
3. Transfer Chrome developer account to SSP. This needs creating a dedicated Google Group (indeed..) as a role owner, then add persons authorized to upload new releases to Chrome Web Store to this Google Group (might need a CWS dev account, costs $5 (really...)), then request Google to change the admin of the extension to the new group.
4. Review open work in the repo, change the brandings and urls where necessary, create new release.

I'm willing to do or coordinate the actions 1 - 4 for the initial transfer.

We can see if sponsorship is available for someone to do the continuous maintenance after that (the few hours per Q mentioned above) and/or look for someone in the extension's community who is willing to that work.

**Comment by meijer** [comment]
Thijs, sorry it took a while. We didn't get to this during the previous board meeting, but in today's  meeting we did. 

The result: the board thanks you for the initiative and decided for SSP to assume responsibility for SAMLtracer.

Our reasoning:
- it is useful for SSP to have a debugging tool
- it's a very useful tool that's in use with a large community. As such it'll increase visibility for SSP

The risk is acceptable, if we have to use money to progress the software it'll be worth it due to it being a useful tool for people deploying SSP. Having said that, we did agree we can probably need to approach funding for SAMLtracer differently, as it's a far wider community. And we need to be transparent which funds are being used for SAMLtracer and which for SSP.

According to Jaime there is a possible contributor, he's agreed to contact him. 

Can you pick up step 1-4?

**Comment by thijskh** [comment]
I've started the process

**Comment by thijskh** [comment]
Step 1 is done, step 4 underway, will work on step 2 and 3. Have invited Jan Kohler as developer with write access.

**Comment by jaimeperez** [comment]
Step 3 in process, I have created a group for people involved, and assigned it as the publishing group for the Chrome extension.  Both step 2 and 3 can be completed as soon as I get confirmation from Jan that he's willing to contribute as maintainer.

**Comment by jaimeperez** [comment]
I got confirmation from Jan and have already welcomed him to the team. Step 3 is now complete and he has the ability to release new versions of the Chrome plugin. Currently waiting for the Mozilla Developer Hub account to fix that too.

**Comment by thijskh** [comment]
All done!

[SAML-Tracer 1.7.1](https://addons.mozilla.org/nl/firefox/addon/saml-tracer/) was published by Jan on addons.mozilla.org and in the Chrome Web Store (pending review on the latter). He has everything he needs to be the new lead maintainer of the extension within the SSP org.
